### ISSUE TITLE
Amplify Deployment

### ISSUE THREAD

**Issue by Rafcin** [bmvantunes/aws-amplify-deploy-test-nx#1]
Sorry to bother you @bmvantunes, I was wondering how did you manage to deploy this repo to amplify, did you not run into issues deploying a monorepo?

**Comment by bmvantunes** [comment]
Yep a spent a good 3 or 4 hours playing around with the AWS amplify configurations in their portal - you can see my struggle looking (and laugh) into my commit history in this repo 😂😅😅😅😅

Finally I landed on something I find "acceptable", but still I have something I don't like... In order to trick aws amplify in seeing this as a nextjs project and work in a monorepo I have to have a fake package.json inside my nextjs project, something I'm not happy with, but couldn't find any documentation around NX, nextjs and amplify (this was my first time playing with AWS amplify, so I'm sure there's a better way to do it - but as I said I found 0 documentation and 0 blogs, 0 everything around nx, nextjs and AWS amplify - this was my best solution in the time I had available yesterday 😅)

**Comment by Rafcin** [comment]
@bmvantunes Did you manage to deploy it? I've opened a few issues and I'm trying to solve it with the hosting team but so far no luck. You should see my commits, I'm 89 commits in and each one says "F*** WHY WON'T THIS WORK" or "I'm loosing brain cells"

**Comment by Rafcin** [comment]
From what I've seen, the approaches offered by the AWS team haven't worked. In one of the threads, someone mentioned to setup a serverless.yml and that could work theoretically.

**Comment by bmvantunes** [comment]
Yes I was able to deploy it, but I had to apply some weird techniques as I said 😅😅

You can have a look here: https://main.d3b3hw63lp2l3m.amplifyapp.com/

**Comment by Rafcin** [comment]
Mind if I ask how you solved the deployment issue? I genuinely can't figure
it out. Also if you can share it, could it be shared the amplify
discord/git, it's killing a few of us 😅

**Comment by Rafcin** [comment]
Is there a certain way you had to set up the amplify.yml for building?

**Comment by Rafcin** [comment]
@bmvantunes Did you have to change the output directories, or rebuild the apps in the deployment process?

**Comment by bmvantunes** [comment]
I'm on my phone now, but the only thing you have to guarantee is that you have inside your next project the compiled .next, a package.JSON and npm install to have node modules 🙂 if you have those 3 it will work 🙂 remind me tomorrow and I can copy paste my yml file 🙂

**Comment by Rafcin** [comment]
Much appreciated! See I've tried that, I had my script run NX build, move .next from the dist folder to the apps folder and then run yarn install and yarn build. It just gets stuck on yarn build and It says it can't run /.bin/next each time.

**Comment by Rafcin** [comment]
And the package.json def the only way to tell Amplify it's a next app, it's stupid we can't set it ourselves but it works. It's just that building phase that's a pain because I can't get it to work. Does that mean that your artifact directory is just .next because you put the .next file inside the apps folder?

**Comment by Rafcin** [comment]
@bmvantunes just leaving a ping because you said to remind you 👌🏻.

**Comment by bmvantunes** [comment]
Thank you for reminding me =D

I had completely forgot about it.
My yml file is:
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - cd .. && cd ..
            - npm ci
        build:
          commands:
            - npx nx build next-app-amplify-nx
            - mv node_modules apps/next-app-amplify-nx/node_modules
            - cd apps/next-app-amplify-nx
            - mv dist/.next .next
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: apps/next-app-amplify-nx
```

Let me know if that helps you :)
I'm doing "- mv node_modules apps/next-app-amplify-nx/node_modules" but npm install inside the app folder would also work.
